### PR TITLE
npm installable

### PR DESCRIPTION
**Pull request by moratori**
# PR Overview

## Background and Purpose

- In preparation for using this repository from other applications in the future, modifications have been made to make it possible to install it using NPM.

## Items implemented

- The directory structure has been changed and the three existing applications have been moved to the `demos` directory.

- Changed the name of the `common` directory to `src`.

- Other settings related to typescript were modified on the assumption that it will be used as a library.

### CODE REVIEW

**Comment by moratori** [comment]
After internal consideration, we have decided not to release this library to npmjs at this stage.
The reason is that the current implementation structure strongly depends on Koa and sqlite, and it is difficult to use the logic of VCI by itself, making it unusable **as a general-purpose library**.

Based on this basis, we would like to add the following two points


- Regarding the included demo application

  - The purpose of the demos is to make it easy for those who are interested in this repository to run the demos.
  - It is implemented so that it can be introduced by only `yarn install` in each app under demos.
  - The following information is for internal stakeholders:
    - The two issues raised (`dist` should be generated automatically and `yarn install` is too slow) have been resolved by using `postinstall` and `preinstall` respectively.

- About embedding this library in your application

  - Since this library is not published on npmjs, it is necessary to manually clone it into the app developer's environment, execute a `yarn build` manually, and then `yarn link` it to your own application.

**Review by ryosuke-wakaba — APPROVED** [review]
This is LGTM. There is no problem for the purpose of this modification, but I thought that the fact that the admin API authentication is fixed to Basic authentication will need to be changed eventually.

**Comment by moratori** [comment]
@ryosuke-wakaba I appreciate your review!
Also, thank you for listing the additional considerations regarding admin authentication. I hope to resolve this in the future so that the library can be used generically.

**Comment by moratori** [comment]
This is just a memorandum.
The reason I chose `postscript` is based on the following information.

https://stackoverflow.com/questions/64158590/how-should-a-typescript-library-be-built-that-is-intended-to-be-install-by-git-u

**Pull request merged**
